import Footer from "@/components/ui/layout/footer";
import { Navbar } from "@/components/ui/layout/navbar";
import { AuthProvider } from "@/providers/auth-provider";
import { CartProvider } from "@/providers/cart-provider";
import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${robotoMono.variable} antialiased`}>
        <div className="min-h-screen flex flex-col antialiased">
          <h1 className="sr-only">Welcome to Crumb & Co Bakery</h1>
          <AuthProvider>
            <CartProvider>
              <Navbar />
              <main className="grow">{children}</main>
              <Footer />
            </CartProvider>
          </AuthProvider>
          <Toaster position="top-center" />
        </div>
      </body>
    </html>
  );
}
